// Generated by scripts/build_from_live.py from the live pistachiocafe.com/careers markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Careers at Pistachio Cafe"
  },
  "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
  "alternates": {
    "canonical": "https://pistachiocafe.com/careers"
  },
  "openGraph": {
    "title": "Careers at Pistachio Cafe",
    "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
    "url": "https://pistachiocafe.com/careers",
    "type": "website",
    "images": [
      {
        "url": "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Careers at Pistachio Cafe",
    "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
    "images": [
      "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696"
    ]
  }
};

export default function Page() {
  return <LivePage slug="careers" />;
}
