// Generated by scripts/build_from_live.py from the live pistachiocafe.com/privacy markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Terms and Policies - Pistachio Cafe"
  },
  "openGraph": {
    "type": "website"
  },
  "twitter": {}
};

export default function Page() {
  return <LivePage slug="privacy" />;
}
