// Generated by scripts/build_from_live.py from the live pistachiocafe.com/ markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Pistachio Cafe | Best Cafe in New Haven, CT | Cafe near me"
  },
  "description": "Pistachio Cafe: the best Cafe in New Haven, CT and other locations. Order directly online today for takeout or delivery. Save money, support local business!",
  "alternates": {
    "canonical": "https://pistachiocafe.com/"
  },
  "openGraph": {
    "title": "Pistachio Cafe | Best Cafe in New Haven, CT | Cafe near me",
    "description": "Pistachio Cafe: the best Cafe in New Haven, CT and other locations. Order directly online today for takeout or delivery. Save money, support local business!",
    "url": "https://pistachiocafe.com/",
    "type": "website",
    "images": [
      {
        "url": "https://pistachiocafe.com/pluto-videos/g1D1GmcwSgLH/bfb0e23b6639397b3423/poster.jpg",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Pistachio Cafe | Best Cafe in New Haven, CT | Cafe near me",
    "description": "Pistachio Cafe: the best Cafe in New Haven, CT and other locations. Order directly online today for takeout or delivery. Save money, support local business!",
    "images": [
      "https://pistachiocafe.com/pluto-videos/g1D1GmcwSgLH/bfb0e23b6639397b3423/poster.jpg"
    ]
  }
};

export default function Page() {
  return <LivePage slug="home" />;
}
