// Generated by scripts/build_from_live.py from the live pistachiocafe.com/page/proudly-serving-new-haven markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Proudly Serving New Haven | Pistachio Cafe"
  },
  "description": "Find out more about Proudly Serving New Haven at Pistachio Cafe",
  "alternates": {
    "canonical": "https://pistachiocafe.com/page/proudly-serving-new-haven"
  },
  "openGraph": {
    "title": "Proudly Serving New Haven | Pistachio Cafe",
    "description": "Find out more about Proudly Serving New Haven at Pistachio Cafe",
    "url": "https://pistachiocafe.com/page/proudly-serving-new-haven",
    "type": "website",
    "images": [
      {
        "url": "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Proudly Serving New Haven | Pistachio Cafe",
    "description": "Find out more about Proudly Serving New Haven at Pistachio Cafe",
    "images": [
      "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696"
    ]
  }
};

export default function Page() {
  return <LivePage slug="page__proudly-serving-new-haven" />;
}
