// Generated by scripts/build_from_live.py from the live pistachiocafe.com/catering markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Pistachio Cafe Catering in New Haven, CT"
  },
  "description": "Order catering from Pistachio Cafe. Freshly prepared, professionally delivered catering for corporate events, private parties, weddings, and more.",
  "alternates": {
    "canonical": "https://pistachiocafe.com/catering"
  },
  "openGraph": {
    "title": "Pistachio Cafe Catering in New Haven, CT",
    "description": "Order catering from Pistachio Cafe. Freshly prepared, professionally delivered catering for corporate events, private parties, weddings, and more.",
    "url": "https://pistachiocafe.com/catering",
    "type": "website",
    "images": [
      {
        "url": "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Pistachio Cafe Catering in New Haven, CT",
    "description": "Order catering from Pistachio Cafe. Freshly prepared, professionally delivered catering for corporate events, private parties, weddings, and more.",
    "images": [
      "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696"
    ]
  }
};

export default function Page() {
  return <LivePage slug="catering" />;
}
