// Generated by scripts/build_from_live.py from the live pistachiocafe.com/page/birthdays--space-rentals markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Private Events | Pistachio Cafe"
  },
  "description": "Find out more about Private Events at Pistachio Cafe",
  "alternates": {
    "canonical": "https://pistachiocafe.com/page/birthdays--space-rentals"
  },
  "openGraph": {
    "title": "Private Events | Pistachio Cafe",
    "description": "Find out more about Private Events at Pistachio Cafe",
    "url": "https://pistachiocafe.com/page/birthdays--space-rentals",
    "type": "website",
    "images": [
      {
        "url": "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Private Events | Pistachio Cafe",
    "description": "Find out more about Private Events at Pistachio Cafe",
    "images": [
      "https://static-content.owner.com/funnel/images/5e40041a-3017-4f4a-bb53-84b99789cf9d?v=4889189696"
    ]
  }
};

export default function Page() {
  return <LivePage slug="page__birthdays--space-rentals" />;
}
