// Generated by scripts/build_from_live.py from the live pistachiocafe.com/911-whalley-ave markup.
import type { Metadata } from "next";
import LivePage from "@/components/LivePage";

export const metadata: Metadata = {
  "title": {
    "absolute": "Pistachio Cafe | Best Cafe in Westville, New Haven | Cafe near me"
  },
  "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
  "alternates": {
    "canonical": "https://pistachiocafe.com/911-whalley-ave"
  },
  "openGraph": {
    "title": "Pistachio Cafe | Best Cafe in Westville, New Haven | Cafe near me",
    "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
    "url": "https://pistachiocafe.com/911-whalley-ave",
    "type": "website",
    "images": [
      {
        "url": "https://pistachiocafe.com/pluto-videos/g1D1GmcwSgLH/bfb0e23b6639397b3423/poster.jpg",
        "alt": "Pistachio Cafe"
      }
    ]
  },
  "twitter": {
    "card": "summary_large_image",
    "title": "Pistachio Cafe | Best Cafe in Westville, New Haven | Cafe near me",
    "description": "Pistachio Cafe Official Website. Save Money Ordering Directly Here. Healthy Options. Fast Service. Friendly Team. Top Rated.",
    "images": [
      "https://pistachiocafe.com/pluto-videos/g1D1GmcwSgLH/bfb0e23b6639397b3423/poster.jpg"
    ]
  }
};

export default function Page() {
  return <LivePage slug="911-whalley-ave" />;
}
